# Generated by Django 2.1.3 on 2018-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('categoryid', models.IntegerField(db_column='categoryId')),
                ('productcode', models.CharField(db_column='productCode', max_length=20)),
                ('revision', models.CharField(max_length=30)),
                ('imagefile', models.TextField(db_column='imageFile')),
                ('genericprice', models.FloatField(db_column='genericPrice')),
                ('zebraprice', models.FloatField(db_column='zebraPrice')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'dt_spareparts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SparepartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('activestate', models.IntegerField(db_column='activeState')),
            ],
            options={
                'db_table': 'dt_sparepart_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpmStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('prio', models.IntegerField()),
                ('allowedusers', models.TextField(db_column='allowedUsers')),
            ],
            options={
                'db_table': 'dt_spm_stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpmStockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.IntegerField(db_column='stockId')),
                ('sparepartid', models.IntegerField(db_column='sparePartId')),
                ('minlevel', models.IntegerField(db_column='minLevel')),
                ('maxlevel', models.IntegerField(db_column='maxLevel')),
                ('stockamount', models.IntegerField(db_column='stockAmount')),
                ('binlocator', models.CharField(db_column='binLocator', max_length=10)),
            ],
            options={
                'db_table': 'dt_spm_stock_items',
                'managed': False,
            },
        ),
    ]
